"""
Simple, SAFE code generator for self_build.

Generates git-applyable unified diffs that only ADD new files by default:
- a skipped pytest file documenting the task
- a TODO note under self_build/artifacts

Why: patches apply cleanly without needing to read or diff existing files,
and they don't break the build (tests are skipped).
"""

from __future__ import annotations

from typing import Dict, Any, Tuple, List
from pathlib import Path
import re
import datetime as _dt


# Repo root (sibling of web_planning)
ROOT = Path(__file__).resolve().parents[3]


def _slug(s: str) -> str:
    s = s.strip().lower()
    s = re.sub(r"[^a-z0-9\-_. ]+", "-", s)
    s = s.replace(" ", "-")
    s = re.sub(r"-+", "-", s)
    return s.strip("-") or "task"


def _posix(p: Path) -> str:
    return p.as_posix()


def _make_add_file_patch(rel_path: str, content: str) -> str:
    """Return a unified diff that adds a new file with given content.
    rel_path should be POSIX-style, relative to repo root.
    """
    lines = content.splitlines()
    body = "\n".join("+" + ln for ln in lines) + (
        "\n" if content and not content.endswith("\n") else ""
    )
    return (
        f"diff --git a/{rel_path} b/{rel_path}\n"
        "new file mode 100644\n"
        "index 0000000..e69de29\n"
        "--- /dev/null\n"
        f"+++ b/{rel_path}\n"
        "@@\n"
        f"{body}"
    )


def _build_task_files(task: Dict[str, Any]) -> List[Tuple[str, str]]:
    """Return a list of (posix_rel_path, content) for files to add."""
    title = str(task.get("title") or task.get("id") or "Untitled Task")
    tid = str(task.get("id") or _slug(title))
    slug = _slug(tid)
    now = _dt.datetime.utcnow().isoformat() + "Z"

    # 1) Skipped pytest documenting task
    test_rel = Path("web_planning/backend/tests") / f"test_auto_{slug}.py"
    test_src = f"""import pytest\n\n\n@pytest.mark.skip(\"Auto-generated placeholder for task: {title}\")\ndef test_placeholder_{slug}():\n    assert True\n"""

    # 2) TODO note under artifacts
    note_rel = Path("web_planning/backend/self_build/artifacts") / f"TODO_{slug}.md"
    note_src = f"""# TODO: {title}\n\n- id: {tid}\n- created: {now}\n\nThis file was auto-generated by self_build.codegen to capture the intent of the task while keeping CI green.\nYou can replace this with concrete implementation steps and link commits here.\n"""

    return [(_posix(test_rel), test_src), (_posix(note_rel), note_src)]


def propose_patch(task: Dict[str, Any]) -> str:
    """Produce a git-applyable patch that adds safe placeholders for the task.

    Returns a unified diff string containing additions for:
    - a skipped pytest under web_planning/backend/tests/
    - a TODO note under web_planning/backend/self_build/artifacts/
    """
    entries = _build_task_files(task)
    diffs = [_make_add_file_patch(rel, src) for rel, src in entries]
    return "\n".join(diffs) + ("\n" if diffs else "")


__all__ = ["propose_patch"]
