from typing import Any, Dict, Iterable, Mapping, Optional, Tuple

SE41_VERSION: str


def classify_readiness(coherence: float, impetus: float) -> str: ...


class SE41Signals:
    coherence: float
    impetus: float
    risk: float
    uncertainty: float
    mirror_consistency: float
    S_EM: float
    ethos: Dict[str, float]
    embodiment: Dict[str, float]
    explain: str
    @property
    def C_realize(self) -> float: ...
    def to_dict(self) -> Dict[str, Any]: ...


class SymbolicEquation41:
    def __init__(self, default_coherence: float = ...) -> None: ...
    def evaluate(self, ctx: Dict[str, Any]) -> SE41Signals: ...
    def evaluate_dict(self, ctx: Dict[str, Any]) -> Dict[str, Any]: ...
    def evaluate_from_summaries(self, summaries: Iterable[Mapping[str, Any]]) -> SE41Signals: ...
    def reality_manifestation(self, Q: float = ...) -> float: ...
    def validate_update_coherence(self, ctx: Mapping[str, Any]) -> float: ...
    def get_coherence_level(self) -> float: ...
    def post_update_recalibration(self) -> None: ...
    def get_current_state_summary(self) -> Dict[str, Any]: ...
    def consciousness_shift(self, delta: float) -> None: ...


class Reality:
    engine: SymbolicEquation41
    def __init__(self, engine: Optional[SymbolicEquation41] = ...) -> None: ...
    def __call__(self, t: Optional[float] = ..., ctx: Optional[Dict[str, Any]] = ...) -> float: ...
    def measure(self, ctx: Dict[str, Any]) -> float: ...


def build_se41_context(*, coherence_hint: float = ..., overrides: Optional[Dict[str, Any]] = ...) -> Dict[str, Any]: ...


def assemble_se41_context_from_summaries(summaries: Iterable[Mapping[str, Any]]) -> Dict[str, Any]: ...


def signals_to_dict(sig: Any) -> Dict[str, Any]: ...


def compute_verification_score(payload: Any) -> float: ...


def suggest_gate(payload: Any, thresholds: Tuple[float, float] = ...) -> str: ...
